language: node_js
sudo: false
node_js:
  - "4"
  - "5"
  - "0.12"

before_script:
  - npm install bower karma-cli -g
  - bower install

script: npm run travis

after_success: NODE_ENV=test cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage