language: node_js
sudo: false
node_js:
  - "0.12"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install bower karma-cli -g
  - bower install

script: npm run travis

after_success: NODE_ENV=test cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage